export * from './is-func'

export * from './is-array'
export * from './is-intersection-of'
export * from './is-iterable'
export * from './is-keyed'
export * from './is-object'
export * from './is-optional'
export * from './is-promise'
export * from './is-record'

export * from './is-shape-of'
export * from './is-tuple-of'
export * from './is-union-of'
export * from './is-unknown'
